name: Test

on: [push]

jobs:
  Type-Check:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 14
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache Dependecies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependecies
        run: yarn install --frozen-lockfile
      - name: Type check js,jsx and ts files
        uses: andoshin11/typescript-error-reporter-action@v1.0.2
